//
// This file generated by rdl 1.5.2. Do not modify!
//

import com.yahoo.rdl.*;
import java.util.*;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

//
// CrudlHandler is the interface that the service implementation must implement
//
public interface CrudlHandler { 
    public Item postItem(ResourceContext context, Item item);
    public void getItem(ResourceContext context, String id, Timestamp ifNewer, GetItemResult result);
    public Item putItem(ResourceContext context, String id, Item item);
    public Item deleteItem(ResourceContext context, String id);
    public ItemListing getItemListing(ResourceContext context, Integer skip, Integer limit);
    public ResourceContext newResourceContext(HttpServletRequest request, HttpServletResponse response);
}
