//
// This file generated by rdl 1.5.2. Do not modify!
//

import com.yahoo.rdl.*;
import java.util.*;
import javax.ws.rs.core.Response;
import javax.ws.rs.WebApplicationException;

public final class GetItemResult {
    private ResourceContext context;
    private String id;
    private int code; //normal result

    GetItemResult(ResourceContext context) {
        this.context = context;
        this.code = 0;
    }

    public boolean isAsync() {
        return false;
    }

    public void done(int code, Item item, Timestamp modified) {
        Response resp = Response.status(code).entity(item)
            .header("Modified", modified)
            .build();
        throw new WebApplicationException(resp);
    }

    public void done(int code) {
        done(code, new ResourceError().code(code).message(ResourceException.codeToString(code)), "");
    }

    public void done(int code, Timestamp modified) {
        done(code, new ResourceError().code(code).message(ResourceException.codeToString(code)), modified);
    }

    public void done(int code, Object entity, Timestamp modified) {
        this.code = code;
        //to do: check if the exception is declared, and that the entity is of the declared type
        WebApplicationException err = new WebApplicationException(Response.status(code).entity(entity)
            .header("Modified", modified)
          .build());
        throw err; //not optimal
    }

}
